// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IHospitalRepo is an autogenerated mock type for the IHospitalRepo type
type IHospitalRepo struct {
	mock.Mock
}

type IHospitalRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *IHospitalRepo) EXPECT() *IHospitalRepo_Expecter {
	return &IHospitalRepo_Expecter{mock: &_m.Mock}
}

// HospitalExists provides a mock function with given fields: hospitalID
func (_m *IHospitalRepo) HospitalExists(hospitalID int) error {
	ret := _m.Called(hospitalID)

	if len(ret) == 0 {
		panic("no return value specified for HospitalExists")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(hospitalID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IHospitalRepo_HospitalExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HospitalExists'
type IHospitalRepo_HospitalExists_Call struct {
	*mock.Call
}

// HospitalExists is a helper method to define mock.On call
//   - hospitalID int
func (_e *IHospitalRepo_Expecter) HospitalExists(hospitalID interface{}) *IHospitalRepo_HospitalExists_Call {
	return &IHospitalRepo_HospitalExists_Call{Call: _e.mock.On("HospitalExists", hospitalID)}
}

func (_c *IHospitalRepo_HospitalExists_Call) Run(run func(hospitalID int)) *IHospitalRepo_HospitalExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *IHospitalRepo_HospitalExists_Call) Return(_a0 error) *IHospitalRepo_HospitalExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IHospitalRepo_HospitalExists_Call) RunAndReturn(run func(int) error) *IHospitalRepo_HospitalExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewIHospitalRepo creates a new instance of IHospitalRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHospitalRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHospitalRepo {
	mock := &IHospitalRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
