// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/vedoalfarizi/hospital-api/internal/dto"

	model "github.com/vedoalfarizi/hospital-api/internal/model"
)

// IPatientRepo is an autogenerated mock type for the IPatientRepo type
type IPatientRepo struct {
	mock.Mock
}

type IPatientRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *IPatientRepo) EXPECT() *IPatientRepo_Expecter {
	return &IPatientRepo_Expecter{mock: &_m.Mock}
}

// GetPatientByID provides a mock function with given fields: id
func (_m *IPatientRepo) GetPatientByID(id string) (*model.Patient, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPatientByID")
	}

	var r0 *model.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Patient, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Patient); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPatientRepo_GetPatientByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPatientByID'
type IPatientRepo_GetPatientByID_Call struct {
	*mock.Call
}

// GetPatientByID is a helper method to define mock.On call
//   - id string
func (_e *IPatientRepo_Expecter) GetPatientByID(id interface{}) *IPatientRepo_GetPatientByID_Call {
	return &IPatientRepo_GetPatientByID_Call{Call: _e.mock.On("GetPatientByID", id)}
}

func (_c *IPatientRepo_GetPatientByID_Call) Run(run func(id string)) *IPatientRepo_GetPatientByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IPatientRepo_GetPatientByID_Call) Return(_a0 *model.Patient, _a1 error) *IPatientRepo_GetPatientByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPatientRepo_GetPatientByID_Call) RunAndReturn(run func(string) (*model.Patient, error)) *IPatientRepo_GetPatientByID_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPatients provides a mock function with given fields: hospitalID, query
func (_m *IPatientRepo) SearchPatients(hospitalID int, query dto.PatientSearchRequest) ([]model.Patient, error) {
	ret := _m.Called(hospitalID, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchPatients")
	}

	var r0 []model.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(int, dto.PatientSearchRequest) ([]model.Patient, error)); ok {
		return rf(hospitalID, query)
	}
	if rf, ok := ret.Get(0).(func(int, dto.PatientSearchRequest) []model.Patient); ok {
		r0 = rf(hospitalID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(int, dto.PatientSearchRequest) error); ok {
		r1 = rf(hospitalID, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPatientRepo_SearchPatients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPatients'
type IPatientRepo_SearchPatients_Call struct {
	*mock.Call
}

// SearchPatients is a helper method to define mock.On call
//   - hospitalID int
//   - query dto.PatientSearchRequest
func (_e *IPatientRepo_Expecter) SearchPatients(hospitalID interface{}, query interface{}) *IPatientRepo_SearchPatients_Call {
	return &IPatientRepo_SearchPatients_Call{Call: _e.mock.On("SearchPatients", hospitalID, query)}
}

func (_c *IPatientRepo_SearchPatients_Call) Run(run func(hospitalID int, query dto.PatientSearchRequest)) *IPatientRepo_SearchPatients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(dto.PatientSearchRequest))
	})
	return _c
}

func (_c *IPatientRepo_SearchPatients_Call) Return(_a0 []model.Patient, _a1 error) *IPatientRepo_SearchPatients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPatientRepo_SearchPatients_Call) RunAndReturn(run func(int, dto.PatientSearchRequest) ([]model.Patient, error)) *IPatientRepo_SearchPatients_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPatientRepo creates a new instance of IPatientRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPatientRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPatientRepo {
	mock := &IPatientRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
