// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/vedoalfarizi/hospital-api/internal/model"
)

// IStaffRepo is an autogenerated mock type for the IStaffRepo type
type IStaffRepo struct {
	mock.Mock
}

type IStaffRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *IStaffRepo) EXPECT() *IStaffRepo_Expecter {
	return &IStaffRepo_Expecter{mock: &_m.Mock}
}

// CreateStaff provides a mock function with given fields: staff
func (_m *IStaffRepo) CreateStaff(staff *model.Staff) (*model.Staff, error) {
	ret := _m.Called(staff)

	if len(ret) == 0 {
		panic("no return value specified for CreateStaff")
	}

	var r0 *model.Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Staff) (*model.Staff, error)); ok {
		return rf(staff)
	}
	if rf, ok := ret.Get(0).(func(*model.Staff) *model.Staff); ok {
		r0 = rf(staff)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Staff) error); ok {
		r1 = rf(staff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IStaffRepo_CreateStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStaff'
type IStaffRepo_CreateStaff_Call struct {
	*mock.Call
}

// CreateStaff is a helper method to define mock.On call
//   - staff *model.Staff
func (_e *IStaffRepo_Expecter) CreateStaff(staff interface{}) *IStaffRepo_CreateStaff_Call {
	return &IStaffRepo_CreateStaff_Call{Call: _e.mock.On("CreateStaff", staff)}
}

func (_c *IStaffRepo_CreateStaff_Call) Run(run func(staff *model.Staff)) *IStaffRepo_CreateStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Staff))
	})
	return _c
}

func (_c *IStaffRepo_CreateStaff_Call) Return(_a0 *model.Staff, _a1 error) *IStaffRepo_CreateStaff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IStaffRepo_CreateStaff_Call) RunAndReturn(run func(*model.Staff) (*model.Staff, error)) *IStaffRepo_CreateStaff_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function with given fields: username
func (_m *IStaffRepo) GetByUsername(username string) (*model.Staff, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *model.Staff
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Staff, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Staff); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Staff)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IStaffRepo_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type IStaffRepo_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - username string
func (_e *IStaffRepo_Expecter) GetByUsername(username interface{}) *IStaffRepo_GetByUsername_Call {
	return &IStaffRepo_GetByUsername_Call{Call: _e.mock.On("GetByUsername", username)}
}

func (_c *IStaffRepo_GetByUsername_Call) Run(run func(username string)) *IStaffRepo_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IStaffRepo_GetByUsername_Call) Return(_a0 *model.Staff, _a1 error) *IStaffRepo_GetByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IStaffRepo_GetByUsername_Call) RunAndReturn(run func(string) (*model.Staff, error)) *IStaffRepo_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// NewIStaffRepo creates a new instance of IStaffRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIStaffRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IStaffRepo {
	mock := &IStaffRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
